### ISSUE TITLE
'/' is stripped from protocol in domain and server

### ISSUE THREAD

**Issue by remcohaszing** [hazart/grunt-escaped-seo#1]
When `options.domain` or `options.server` starts with `http://`, it is changed to `http:/` in the sitemap.

**Comment by hazart** [comment]
Hi, I've fixed this bug in the version 0.3.0 You can update. It was up to date on npm but not on github.

**Comment by remcohaszing** [comment]
I already had version 0.3.0 installed. The bug still exists.

**Comment by hazart** [comment]
Ok, I've changed for the redirection but not for the sitemap. It should be ok now with 0.3.1

**Comment by remcohaszing** [comment]
Thanks for the really fast reply and fix!
